# Generated by Django 4.0.1 on 2022-04-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='billingAddress1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_city',
            new_name='billingCity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_country',
            new_name='billingCountry',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_name',
            new_name='billingName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_postcode',
            new_name='billingPostcode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='shippingAddress1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_city',
            new_name='shippingCity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_country',
            new_name='shippingCountry',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_name',
            new_name='shippingName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_postcode',
            new_name='shippingPostcode',
        ),
    ]
